### ISSUE TITLE
Passwords with special characters cause the app to fail

### ISSUE THREAD

**Issue by mandreko-ts** [zyn3rgy/LdapRelayScan#17]
I'm trying to utilize this with a password that is fairly strong, and it fails. However, if I use a username with a very simplistic password, it works fine.  Here's the error when I do it with a password containing special characters:

```
[~/LdapRelayScan] # python3.9 LdapRelayScan.py -method BOTH -dc-ip 192.168.1.1 -u complexuser -p 'Du8Yl;\KF?(~@wl'

~Domain Controllers identified~
   dc2.redacted.com
   drdc1.redacted.com

~Checking DCs for LDAP NTLM relay protections~
   dc2.redacted.com
      [+] (LDAP)  SERVER SIGNING REQUIREMENTS NOT ENFORCED!
something went wrong during ldaps_withEPA bind:Port could not be cast to integer value as 'Du8Yl;\\KF'

Something went wrong...
For troubleshooting:
ldapsChannelBindingAlwaysCheck - False
ldapsChannelBindingWhenSupportedCheck: None
```

Without digging in too far, I would suspect it to be [line 54](https://github.com/zyn3rgy/LdapRelayScan/blob/main/LdapRelayScan.py#L54) causing the issue. 
```
url = 'ldaps+ntlm-password://'+inputUser + ':' + inputPassword +'@' + dcTarget
```

You can see that the first part of the password is being included as the port number to connect to in the error message, which leads me to this speculation. Passwords may need to be escaped somehow?

**Comment by zyn3rgy** [comment]
Hey @mandreko-ts !

I was able to reproduce:
`(venv) user@host:/LdapRelayScan# proxychains4 -q python3 LdapRelayScan.py -dc-ip 10.0.0.20 -m BOTH -u charles -p 'Du8Yl;\KF?(~@wl'

~Domain Controllers identified~
   dc2.citadel.lab
   DC1.citadel.lab

~Checking DCs for LDAP NTLM relay protections~
   dc2.citadel.lab
      [-] ERROR: socket connection error while opening: [Errno 111] Connection refused
   DC1.citadel.lab
      [+] (LDAP)  SERVER SIGNING REQUIREMENTS NOT ENFORCED! 
something went wrong during ldaps_withEPA bind:Port could not be cast to integer value as 'Du8Yl;\\KF'

Something went wrong...
For troubleshooting:
ldapsChannelBindingAlwaysCheck - False
ldapsChannelBindingWhenSupportedCheck: None
`

Interesting to me that failure happens _after_ the LDAP check, because checking LDAPS doesn't require auth. Hoping to spend a few debugging this soon, but wanted to update in the meantime. Thanks for the note.

**Comment by zyn3rgy** [comment]
So it looks like you were right, that string on [line 54](https://github.com/zyn3rgy/LdapRelayScan/blob/main/LdapRelayScan.py#L55) that you mentioned is passed into msldap's [LDAPConnectionFactory.from_url()](https://github.com/skelsec/msldap/blob/fe0d7faa75b935db544c7fbd68e5409e24a8af3b/msldap/commons/factory.py#L78) which doesn't seem to appreciate more complicated passwords. Luckily for us, the LDAPS / channel binding protection status can be determined without successful NTLM challenge/response - [documented here](https://github.com/zyn3rgy/LdapRelayScan#ldaps-channel-binding-token-requirements) back when I was digging into this technique.

The [commit](https://github.com/zyn3rgy/LdapRelayScan/commit/347ed294bab13b06f97b0d07bf62a3980758aa9d) above is a temporary fix, basically as if the password param wasn't provided at all for that portion of the check. The proper fix would be to sift through the previously mentioned msldap function and figure out how we could appropriately pass a more complex string.

I'll leave this open for a bit in case anyone else wants to take a stab, otherwise I'll close out shortly. This resolved the issue in my testing, but let me know if it's not working for you!

**Comment by zyn3rgy** [comment]
Also if you experience any escaping or parsing issues associated with complex passwords in the future, an alternative would be to convert the password to it's NT hashed format and supply the password using the `-nthash` parameter.
